SELECT * FROM EMP

SELECT * FROM DEPT

INSERT INTO DEPT VALUES(60,'DEVELOPMENT','PALALTO')
DELETE DEPT WHERE LOC = 'PALALTO'

INSERT INTO EMP VALUES (1299,'ALI','TESTER',7782,'10-15-2024',1100,NULL,0);
UPDATE EMP SET dept = 50 WHERE empno = 1299

-- UPDATE NAME & JOB OF EMPLOYEE WHERE ID  = 1299

UPDATE EMP SET ename = 'ZAIN' , job = 'DESIGNER' WHERE empno = 1299 
UPDATE EMP SET DEPT  = 60 , JOB = 'DEVELOPER'  , SAL  = 2300 WHERE EMPNO = 1299
SELECT * FROM EMP
SELECT * FROM EMP WHERE EMPNO  < 7000


DELETE FROM EMP WHERE EMPNO < 7000
SELECT * FROM EMP WHERE ENAME = 'ZAIN'


SELECT * FROM EMP JOIN DEPT ON EMP.DEPT = DEPT.DEPTNO 

SELECT * FROM EMP ORDER BY DEPT,ENAME DESC

SELECT  MIN(SAL) FROM EMP
SELECT MAX(SAL) FROM EMP

SELECT ENAME  FROM EMP WHERE SAL = MAX(SAL)

SELECT * FROM EMP

SELECT COUNT( DISTINCT DEPT ) FROM EMP 

-- ENAME STARTING LETTER EIETHER BE FROM A OR B AND AFTER I DON'T KNOW
SELECT * FROM EMP WHERE ENAME LIKE '[AB]%'

SELECT * FROM EMP WHERE ENAME LIKE '[A-Z]%'  -- GET EMPLOYEE NAME STARTING A TO Z LETTER (OBOUSIVLY ALL)


SELECT SAL*100 FROM EMP

SELECT * FROM DEPT

SELECT TOP 3 *  FROM EMP

-- SELECT * FROM emp LIMIT 6; (not for ssms  , but for other db's and mysql)
-- Use TOP clause in query

-- SELECT * FROM EMP FETCH FIRST 3 ROWS ONLY;


SELECT * FROM EMP ORDER BY SAL DESC

SELECT CEILING(SUM(SAL)) FROM EMP

SELECT SAL,COMM FROM EMP WHERE COMM IS NOT NULL
