USE companydb;

SELECT TOP 5 * FROM EMP ORDER BY ENAME DESC
BEGIN
UPDATE EMP SET COMM = 750;

ROLLBACK;

DELETE FROM EMP WHERE EMPNO  = 1400

SELECT MAX(SAL) FROM EMP
SELECT MIN(SAL) FROM EMP
SELECT CEILING(AVG(SAL)) FROM EMP;

-- SELECT * FROM EMP WHERE SAL= (SELECT MAX(SAL) FROM EMP);


SELECT MAX(SAL) - MIN(SAL) FROM EMP;

SELECT COUNT(*) AS EMPLOYEE_COUNT  FROM EMP WHERE SAL   >= 1000;

SELECT EMPNO AS EMPLOYEE_NUMBER, ENAME AS EMPLOYEE_NAME  FROM EMP

DELETE FROM EMP  WHERE ENAME  = 'ALLEN'

SELECT SAL*12 AS YEARLY_SALARY FROM EMP ORDER BY  SAL DESC

SELECT ENAME AS EMPLOYEE_NAME , SAL- (SAL*0.12) AS DECREMENT FROM EMP


SELECT  ENAME , SAL FROM EMP WHERE SAL % 2  = 0 -- EQUAL(=) TO ZERO  
SELECT ENAME , SAL  FROM EMP WHERE SAL % 2 <> 0 -- NOT_EQUAL(<>) TO ZERO  also (!=)


-- NOT DIRECTLY JOIN  BUT IT'S JOIN BABY

		-- AFTER TABLE NAME IF YOU WANT TO SET NICKNAME OF TABLE YOU SHOUD DO 
SELECT * FROM EMP E, DEPT D

SELECT COUNT(*) AS Department FROM DEPT

SELECT COUNT(*) AS Employee FROM EMP

SELECT COUNT(*) FROM EMP  , DEPT
SELECT * FROM EMP, DEPT WHERE EMP.DEPT = DEPT.DEPTNO 

SELECT * FROM EMP JOIN DEPT ON EMP.DEPT = DEPT.DEPTNO

INSERT INTO EMP VALUES (7001,'HARRY','MANAGER',7839, '06-11-2023',3520,500,50)

SELECT * FROM EMP INNER JOIN DEPT ON EMP.DEPT =  DEPT.DEPTNO
SELECT * FROM EMP RIGHT JOIN DEPT ON EMP.DEPT = DEPT.DEPTNO
SELECT * FROM DEPT LEFT JOIN EMP ON EMP.DEPT = DEPT.DEPTNO	

SELECT * FROM EMP CROSS JOIN DEPT 


INSERT INTO EMP VALUES (7008,'ASLAM','ADMIN',7839, '01-01-2024',600,250.00,88)

SELECT * FROM EMP FULL OUTER JOIN DEPT ON EMP.DEPT = DEPT.DEPTNO	

