--select * from emp

-- Query 1 --select empno , ename , sal from emp where job = 'MANAGER';

-- Query 2 SELECT * FROM EMP WHERE DEPT = 30

-- QUERY 3 SELECT EMPNO , ENAME , HIREDATE FROM EMP WHERE hiredate > '1982-01-01'


 --QUERY 4  SELECT ENAME , JOB , SAL , COMM FROM EMP WHERE COMM  >= 0

-- QUERY 5 SELECT EMPNO ,  ENAME  , SAL FROM EMP WHERE SAL BETWEEN 1500 AND 3000 

-- Query 6 SELECT EMPNO , ENAME  , SAL  , DEPT FROM EMP WHERE (DEPT = 30 OR DEPT = 40) AND (SAL > 2000)


-- QUERY 7 SELECT DNAME , LOC FROM DEPT

-- QUERY 8 SELECT ENAME  , JOB  FROM EMP WHERE JOB IN ('MANAGER','ANALYST');

-- QUERY  9 SELECT DEPTNO , DNAME FROM DEPT WHERE LOC  = 'CHICAGO'

-- QUERY 10 SELECT ENAME FROM MP WHERE ENAME LIKE '%E';
-- QUERY 11 SELECT ENAME FROM EMP WHERE ENAME LIKE '%AM%'

-- QUERY 12 SELECT ENAME FROM EMP WHERE ENAME LIKE 'J%S'

-- QUERY 13 SELECT ENAME FROM EMP WHERE JOB LIKE '%MAN'

-- QUERY 14 SELECT ENAME , HIREDATE FROM EMP WHERE HIREDATE LIKE '1981%'	 

-- QUERY 15 SELECT ENAME  , JOB  , SAL FROM EMP WHERE SAL   > 2500 















